spring:
  h2.console:
    enabled: true
    path: '/console'
  datasource:
    url: 'jdbc:h2:file:/Users/mateusz.chrzonstowsk/Downloads/todo-app/todo-db'
  jpa:
    hibernate:
      ddl-auto: validate
